DROP TABLE ROLE_PRIVILEGE CASCADE CONSTRAINTS;
DROP TABLE PRIVILEGE CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE ROLE CASCADE CONSTRAINTS;
DROP TABLE AUTHOR CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE CATEGORY
(
    CATEGORY_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME        VARCHAR2(30) NOT NULL
);

CREATE TABLE AUTHOR
(
    AUTHOR_ID   INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    FIRST_NAME  VARCHAR2(30) NOT NULL,
    LAST_NAME   VARCHAR2(30) NOT NULL,
    RATING      INT,
    VOTES       INT,
    WEBSITE     VARCHAR2(30),
    CATEGORY_ID INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID)
);

CREATE TABLE BOOK
(
    BOOK_ID         INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    TITLE           VARCHAR2(50) NOT NULL,
    ISBN            VARCHAR2(30) NOT NULL,
    PAGE_COUNT      INT,
    LANGUAGE        VARCHAR2(10),
    PUBLISHER       VARCHAR2(30),
    PUBLISHING_DATE DATE,
    RATING          INT,
    VOTES           INT,
    CATEGORY_ID     INT,
    AUTHOR_ID       INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (AUTHOR_ID)
);


CREATE TABLE ROLE
(
    ROLE_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME    VARCHAR2(30) NOT NULL
);

CREATE TABLE PRIVILEGE
(
    PRIVILEGE_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME         VARCHAR2(30) NOT NULL,
    DESCRIPTION  VARCHAR2(30) NOT NULL
);

CREATE TABLE ROLE_PRIVILEGE
(
    ROLE_PRIVILEGE_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    ROLE_ID           INT,
    PRIVILEGE_ID      INT,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID),
    FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGE (PRIVILEGE_ID)
);

CREATE TABLE USERS
(
    USER_ID      INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    USERNAME     VARCHAR2(30) NOT NULL,
    PASSWORD     VARCHAR2(30) NOT NULL,
    EMAIL        VARCHAR2(30) NOT NULL,
    FIRST_NAME   VARCHAR2(30),
    LAST_NAME    VARCHAR2(30),
    BIRTH_DATE   DATE,
    GENDER       VARCHAR2(5),
    PHONE_NUMBER VARCHAR2(30),
    ROLE_ID INT NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);


INSERT  INTO CATEGORY (NAME) VALUES ('Literatura obyczajowa');
INSERT  INTO CATEGORY (NAME) VALUES ('Kryminał');
INSERT INTO CATEGORY (NAME) VALUES ('Fantastyka');
INSERT  INTO CATEGORY (NAME) VALUES ('Kryminał');
INSERT  INTO CATEGORY (NAME) VALUES ('Horror');
INSERT  INTO CATEGORY (NAME) VALUES ('Literatura młodzieżowa');

INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Stephenie', 'Meyer', 6.7, 9102, 'www.stephenie-meyer.com', 1);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Nicholas', 'Sparks', 5.4, 4001, 'www.nicholas-sparks.com', 1);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Cecelia', 'Ahern', 7.5, 3711, 'www.cec-ahern.com', 1);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Stieg', 'Larsson', 6.5, 2209, 'www.stieg-larsson.com', 2);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Dan', 'Brown', 8.1, 10931, 'www.dan-brown.com', 2);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('J.R.R', 'Tolkien', 8.3, 12541, 'www.tolkien.com', 3);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Andrzej', 'Sapkowski', 7.9, 9100, 'www.sapkowski.com', 3);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Paula', 'Hawkins', 4.3, 6251, 'www.paula-hawkins.com', 4);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Mario', 'Puzo', 9.3, 12031, 'www.mario-puzo.com', 4);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Stephen', 'King', 9.1, 9102, 'www.stepen-king.com', 5);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Bram', 'Stoker', 6.4, 7162, 'www.bram-stoker.com', 5);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Holly', 'Black', 4.4, 1213, 'www.holy-black.com', 6);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Beth', 'Reekles', 5.4, 812, 'www.beth-reekles.com', 6);
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, RATING, VOTES, WEBSITE, CATEGORY_ID) VALUES ('Zuzanna', 'Kordel', 3.4, 615, 'www.zuzanna-kordel.com', 6);


INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Love, Rosie', '12788394039887', 172, 'Polski', 'Akurat', '20151109', 6.7, 103, 1, 1);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Pamiętnik', '85726351628935', 236, 'Polski', 'Albatros', '19951217', 3.2, 818, 1, 2);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Zmierzch', '9003948812366', 416, 'Polski', 'Wydawnictwo Dolnośląskie', '20070101', 2.7, 14039, 1, 3);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Mężczyźni, którzy nienawidzą kobiet', '9788375540598', 126, 'Polski', 'Czarna Owca', '20081104', 6.7, 3918, 2, 4);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Kod Leonarda da Vinci', '9788366512474', 568, 'Polski', 'Sonia Draga', '20081104', 7.5, 12930, 2, 5);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Anioły i Demony', '9788366512429', 560, 'Polski', 'Sonia Draga', '20200624', 8.1, 14263, 2, 5);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Hobbit', '9788381162647', 304, 'Polski', 'Zysk i S-ka', '20180212', 8.5, 7652, 3, 6);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Ostatnie życzenie', '9788375780635', 332, 'Polski', 'superNOWA', '20141101', 8.7, 18201, 3, 7);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Krew Elfów', '9788375780659', 340, 'Polski', 'superNOWA', '20141028', 9.1, 13101, 3, 7);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Dziewczyna z pociągu', '9788380316904', 328, 'Polski', 'Świat Książki', '20160914', 8.9, 9012, 4, 8);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Ojciec chrzestny', '9788381250535', 480, 'Polski', 'Albatros', '20171115', 9.7, 19201, 4, 9);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Smętarz dla zwierzaków', '9788381690584', 416, 'Polski', 'Prószyński i S-ka', '20190423', 9.3, 12371, 5, 10);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Miasteczko Salem', '98813059182584', 453, 'Polski', 'Prószyński i S-ka', '20181017', 8.1, 9018, 5, 10);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('To', '9788381257022', 1104, 'Polski', 'Prószyński i S-ka', '20190814', 8.6, 13847, 5, 10);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Dracula', '9788377312872', 428, 'Polski', 'Prószyński i S-ka', '20180116', 7.7, 7162, 5, 11);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Żelazna Kraina', '9788376869629', 352, 'Polski', 'Jaguar', '20210421', 4.7, 120, 5, 12);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Za kółkiem przez Stany', '9788366575929', 211, 'Polski', 'Insignis', '20210414', 3.7, 71, 5, 13);
INSERT INTO BOOK (TITLE, ISBN, PAGE_COUNT, LANGUAGE, PUBLISHER, PUBLISHING_DATE, RATING, VOTES, CATEGORY_ID, AUTHOR_ID)
    VALUES ('Najlepsze przed nami', '9788324060283', 336, 'Polski', 'Chilli Books', '20210414', 5.7, 182, 5, 14);


INSERT INTO ROLE (NAME) VALUES ('ADMIN');
INSERT INTO ROLE (NAME) VALUES ('USER');

INSERT INTO PRIVILEGE (NAME, DESCRIPTION) VALUES ('SUPERPOWER', 'Can do anything');
INSERT INTO PRIVILEGE (NAME, DESCRIPTION) VALUES ('NO_POWER', 'Can''t do nothing');

INSERT INTO ROLE_PRIVILEGE (ROLE_ID, PRIVILEGE_ID) VALUES (1, 1);
INSERT INTO ROLE_PRIVILEGE (ROLE_ID, PRIVILEGE_ID) VALUES (2, 2);

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER, PHONE_NUMBER, ROLE_ID)
    VALUES ('zaleskix', 'zaleskix', 'daniel.zaleski9@gmail.com', 'Daniel', 'Załęski', '19951009', 'M', '+48-111-111-111', 1);
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER, PHONE_NUMBER, ROLE_ID)
    VALUES ('test_user', 'user', 'user@gmail.com', 'User', 'Name', '19941111', 'M', '+48-222-222-222', 2);
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER, PHONE_NUMBER, ROLE_ID)
    VALUES ('test_admin', 'admin', 'admin@gmail.com', 'Admin', 'Admin', '20011111', 'M', '+48-333-333-333', 1);





